# tasks file
---
- name: check | enabled
  ansible.builtin.systemd:
    name: "{{ item.unit }}"
    enabled: "{{ item.enabled }}"
  with_items: "{{ (systemd_service_files + systemd_unit_files) | selectattr('enabled', 'defined') | list }}"
  tags:
    - systemd-check-enabled

- name: check | state
  ansible.builtin.systemd:
    name: "{{ item.unit }}"
    state: "{{ item.state }}"
  with_items: "{{ (systemd_service_files + systemd_unit_files) | selectattr('state', 'defined') | list }}"
  tags:
    - systemd-check-state

- name: check | masked
  ansible.builtin.systemd:
    name: "{{ item.unit }}"
    masked: "{{ item.masked }}"
  with_items: "{{ (systemd_service_files + systemd_unit_files) | selectattr('masked', 'defined') | list }}"
  tags:
    - systemd-check-masked
