# tasks file
---
- block:

  - include: install.yml
    tags:
      - configuration
      - systemd
      - systemd-install

  - include: configure.yml
    tags:
      - configuration
      - systemd
      - systemd-configure

  - include: services.yml
    tags:
      - configuration
      - systemd
      - systemd-services

  - include: units.yml
    tags:
      - configuration
      - systemd
      - systemd-units

  - include: check.yml
    tags:
      - configuration
      - systemd
      - systemd-check

  when: ansible_service_mgr == 'systemd'
